POST http://localhost:3000/auth/log-in
Content-Type: application/json
{
    "username": "testuser",
    "password": "12345678"
}
    

POST http://localhost:3000/users
Content-Type: application/json
{
    "username": "testuser",
    "email": "example@email.com",
    "password": "12345678"
}
